# Moved /etc/zshenv to /etc/zprofile in order for VIM to get the right $PATH 

# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
